version: '3'
services:
  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: apidatabase
      POSTGRES_USER: apiusername
      POSTGRES_PASSWORD: apipassword
    ports:
    - 5432:5432
